### PR TITLE
Create tsao-clara.yml

### PR DESCRIPTION
**Pull request by babycarrot**
Please add me - sorry it took me so long to get around to this! Let me know if there is anything else I need to do! 

THANK YOU FOR ALL THE HELP!

### CODE REVIEW

**Comment by rossdakin** [comment]
On it.

**Comment by babycarrot** [comment]
you are the best Ross- thank you!

On Mon, Apr 25, 2016 at 3:51 PM, Ross Dakin <notifications@github.com>
wrote:

> On it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/presidential-innovation-fellows/pif-website/pull/109#issuecomment-214497782>
>



-- 
Clara Tsao  <http://www.claratsao.com>
Presidential Innovation Fellow
c: 202-340-9053
@tweetclarita
www.pif.gov | www.claratsao.com

**Comment by babycarrot** [comment]
Thanks for the help Ross- somehow I'm still not appearing on the page 😿.
Is there anything else I should fill out?

Sent from my iPhone

On Apr 25, 2016, at 3:57 PM, Ross Dakin <notifications@github.com> wrote:

Closed #109
<https://github.com/presidential-innovation-fellows/pif-website/pull/109>.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/presidential-innovation-fellows/pif-website/pull/109#event-640544728>

**Comment by rossdakin** [comment]
Nope, we just need to ship the site. Waiting for a pic from John first. Let
me know if it's time sensitive and we can change some things up.

On Tuesday, April 26, 2016, Clara Tso <notifications@github.com> wrote:

> Thanks for the help Ross- somehow I'm still not appearing on the page 😿.
> Is there anything else I should fill out?
>
> Sent from my iPhone
>
> On Apr 25, 2016, at 3:57 PM, Ross Dakin <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> Closed #109
> <https://github.com/presidential-innovation-fellows/pif-website/pull/109>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <
> https://github.com/presidential-innovation-fellows/pif-website/pull/109#event-640544728
> >
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/presidential-innovation-fellows/pif-website/pull/109#issuecomment-214759902>
>


-- 
Ross Dakin
Presidential Innovation Fellow
whitehouse.gov/innovationfellows
(202) 286-0143
ross.dakin@pif.gov

**Comment by babycarrot** [comment]
Got it 🙌💪👌🏻 no urgency haha just took me a long while to add myself 😂

Sent from my iPhone

On Apr 26, 2016, at 10:18 AM, Ross Dakin <notifications@github.com> wrote:

Nope, we just need to ship the site. Waiting for a pic from John first. Let
me know if it's time sensitive and we can change some things up.

On Tuesday, April 26, 2016, Clara Tso <notifications@github.com> wrote:

> Thanks for the help Ross- somehow I'm still not appearing on the page 😿.
> Is there anything else I should fill out?
>
> Sent from my iPhone
>
> On Apr 25, 2016, at 3:57 PM, Ross Dakin <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> Closed #109
> <https://github.com/presidential-innovation-fellows/pif-website/pull/109>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <
>
https://github.com/presidential-innovation-fellows/pif-website/pull/109#event-640544728
> >
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <
https://github.com/presidential-innovation-fellows/pif-website/pull/109#issuecomment-214759902
>
>


-- 
Ross Dakin
Presidential Innovation Fellow
whitehouse.gov/innovationfellows
(202) 286-0143
ross.dakin@pif.gov

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/presidential-innovation-fellows/pif-website/pull/109#issuecomment-214760255>

**Pull request closed without merging**
