### PR TITLE
Documentation Updates

### PR DESCRIPTION
**Pull request by s2t2**
Additions:

  + Development setup instructions.

Revisions:

  + Differentiate between which requirements and setup instructions are necessary for development vs deployment

Comments/Questions:

  + If the `s3_website` gem is being used for deployment, should it be listed as a dependency in the `Gemfile`? Perhaps in the `:production` group?

### CODE REVIEW

**Comment by s2t2** [comment]
Hey @bwillman could you review this PR? I don't seem to have permissions to request a reviewer via the GitHub interface. If you have any ideas on how to fix that, I'd appreciate it as well.

**Comment by bwillman** [comment]
Mike - are we even using S3 at this point? I'm not clear what or where that is being used. 

Its now hosted on Federalist - and the images are in the repo. What do you think?

**Comment by s2t2** [comment]
Haha I'm new here. If there's no use for s3 anymore, I will remove the related documentation and gem from the Gemfile. So @bwillman how do we push to production? What are the deployment commands?

**Comment by rossdakin** [comment]
cc @wslack

**Comment by wslack** [comment]
You can use S3 on your own; I don't know how your site's code works. If everything for the site is in the repo, though, then Federalist takes care of the images (I would think) - unless you are explicitly calling from S3.

Federalist doesn't have resources to jump in on PRs like this. I would read up at federalist-docs.18f.gov and ask questions in #federalist-support in Slack.

**Comment by wslack** [comment]
I offered @joshuadifrances to do a Federalist class for the new cohort....maybe that should be planned?

**Comment by s2t2** [comment]
I just configured federalist and did some production deploys. Merging to master deployed a new build to production. Will update the docs to reflect this information.

**Comment by s2t2** [comment]
Closing this PR in favor of #141 . Join the conversation over there?

**Pull request closed without merging**
