### PR TITLE
Add Treasury FinTech & Cyber detail

### PR DESCRIPTION
**Pull request by hobbez**

### CODE REVIEW

**Comment by s2t2** [comment]
Hey @hobbez can you add a `.yml` extension to this file, and can you also rebase? Then ping me and I will merge.

**Comment by hobbez** [comment]
@s2t2 - Don't recall what this updates on the PIF site, but .yml ext added. I used GH's web i/f, so I think rebasing is automatic; if not let me know web steps. Thanks!

**Comment by s2t2** [comment]
Yeah, I erroneously asked for a rebase. Sorry.

**Comment by s2t2** [comment]
This looks good from a code perspective. Because it involves adding a new project that I'm unfamiliar with, I've also asked @joshuadifrances for a contextual review.

**Comment by joshuadifrances** [comment]
Approved

**Pull request merged**
