### PR TITLE
WIP Project Page

### PR DESCRIPTION
**Pull request by lukad03**
This commit is a work in progress for creating project-specific pages. It also removes unnecessary styles from the site's footer, and installs bourbon and neat.
- Create project page mock
- Remove unnecessary footer styles
- Install bourbon
- Install neat

### CODE REVIEW

**Comment by rossdakin** [comment]
Cool stuff.

Note to self (or anyone else): may want to do [this](https://github.com/presidential-innovation-fellows/apps-gov/pull/80) here too.

**Comment by lukad03** [comment]
@rossdakin Resolved in https://github.com/presidential-innovation-fellows/pif-website/pull/104

**Comment by s2t2** [comment]
Given the current state of the website, are these changes still desired? Moreover, I'm trying to gauge whether this PR is active or close-able?

**Comment by rossdakin** [comment]
Good to close from my perspective.

**Pull request closed without merging**
