### PR TITLE
Update home page

### PR DESCRIPTION
**Pull request by rossdakin**
Update video on home page.

screen shot 2017-01-29 at 1 57 41 pm

### CODE REVIEW

**Comment by rossdakin** [comment]
Attn: @lukad03 @adamsfallen

**Comment by RobertLRead** [comment]
I think updating the site to make it less partisan is extremely important.  I recommend this pull request and others be processed.

**Comment by s2t2** [comment]
Given the current homepage, is this change still desired, or is this PR closable?

**Comment by rossdakin** [comment]
Kill it.

**Pull request closed without merging**
