### PR TITLE
Add profile for Steven Babitch

### PR DESCRIPTION
**Pull request by rossdakin**
Look good, @sbabitch?

----
screen shot 2015-11-04 at 5 29 08 pm

----
screen shot 2015-11-04 at 5 29 21 pm

### CODE REVIEW

**Comment by sbabitch** [comment]
Looks great.  Two minor changes on the full bio... in RED.

Steve’s work lies at the intersection of social science, business strategy,
technology and design, He builds new products, platforms and policy,
humanizing their value. In 2015, Steve founded Steven Babitch Design, LLC,
focused on innovation in both private and public sectors. Previously, he
worked for design consultancies Doblin and IA Collaborative, working across a
range of sectors including computer hardware, automotive and health care.
He collaborated with the Mayo Clinic to establish their Center for
Innovation and helped define the next-gen web platform for United Airlines.
He’s done work focused on urban innovation, collaborating with CEOs for
Cities on the challenge of keeping young families living in cities. This
work was cited in The Wall Street Journal article, “Cities Want Young
Families to Play and Stay”.


Thanks Ross!

On Wed, Nov 4, 2015 at 5:29 PM, Ross Dakin <notifications@github.com> wrote:

> Look good, @sbabitch <https://github.com/sbabitch>? [image: screen shot
> 2015-11-04 at 5 29 08 pm]
> <https://cloud.githubusercontent.com/assets/44956/10954111/94489da2-8319-11e5-8fdf-bee9a905ca2a.png>
>
> [image: screen shot 2015-11-04 at 5 29 21 pm]
> <https://cloud.githubusercontent.com/assets/44956/10954110/94444162-8319-11e5-8632-2c2c6eef3720.png>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/presidential-innovation-fellows/pif-website/pull/87
> Commit Summary
>
>    - Add profile for Steven Babitch
>
> File Changes
>
>    - *A* _data/fellows/babitch-steven.yml
>    <https://github.com/presidential-innovation-fellows/pif-website/pull/87/files#diff-0>
>    (16)
>    - *A* assets/images/2015/babitch-steven-headshot.jpg
>    <https://github.com/presidential-innovation-fellows/pif-website/pull/87/files#diff-1>
>    (0)
>
> Patch Links:
>
>    -
>    https://github.com/presidential-innovation-fellows/pif-website/pull/87.patch
>    -
>    https://github.com/presidential-innovation-fellows/pif-website/pull/87.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/presidential-innovation-fellows/pif-website/pull/87>.
>



-- 
Presidential Innovation Fellow
White House Presidential Innovation Fellows
https://www.whitehouse.gov/innovationfellows
202.344.5806

**Comment by rossdakin** [comment]
@sbabitch — color got stripped. 

Email me directly or call out in another way?

Or just send me the full text anew.

**Comment by sbabitch** [comment]
Oh sorry! I just meant use that content as the newer version. All black
text for sure.

Sent from my iPhone

On Nov 4, 2015, at 7:04 PM, Ross Dakin <notifications@github.com> wrote:

@sbabitch <https://github.com/sbabitch> — color got stripped.

Email me directly or call out in another way?

Or just send me the full text anew.

—
Reply to this email directly or view it on GitHub
<https://github.com/presidential-innovation-fellows/pif-website/pull/87#issuecomment-153909907>
.

**Comment by rossdakin** [comment]
I can't see red.

Can you callout the changes in a different way or just send the full text
with your changes included?

On Wednesday, November 4, 2015, Steven Babitch <notifications@github.com>
wrote:

> Oh sorry! I just meant use that content as the newer version. All black
> text for sure.
>
> Sent from my iPhone
>
> On Nov 4, 2015, at 7:04 PM, Ross Dakin <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> @sbabitch <https://github.com/sbabitch> — color got stripped.
>
> Email me directly or call out in another way?
>
> Or just send me the full text anew.
>
> —
> Reply to this email directly or view it on GitHub
> <
> https://github.com/presidential-innovation-fellows/pif-website/pull/87#issuecomment-153909907
> >
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/presidential-innovation-fellows/pif-website/pull/87#issuecomment-153911549>
> .
>


-- 

Ross Dakin
Presidential Innovation Fellow
whitehouse.gov/innovationfellows
(202) 286-0143
ross.dakin@pif.gov

**Comment by sbabitch** [comment]
Ah ok. Full text below...

*Brief bio*

Design Strategist that humanizes technology, transforming user needs into
viable products, platforms, and policy. Mentor @MATTERChicago. Emerging
Leader @ChicagoCouncil. Lived in Chicago. Imported from Detroit.


*Full bio*

Steve’s work lies at the intersection of social science, business strategy,
technology and design, He builds new products, platforms and policy,
humanizing their value. In 2015, Steve founded Steven Babitch Design, LLC,
focused on innovation in both private and public sectors. Previously, he
worked for design consultancies Doblin and IA Collaborative, working across
a range of sectors including computer hardware, automotive, consumer goods
and health care. He collaborated with the Mayo Clinic to establish their
Center for Innovation and helped define the next-generation web platform
for United Airlines. He’s done work focused on urban innovation, including
a collaboration with CEOs for Cities on the challenge of keeping young
families living in cities. This work was cited in The Wall Street Journal
article, “Cities Want Young Families to Play and Stay”.

Steve’s teaching experience includes lecturing at the Segal Design
Institute at Northwestern University and CEDIM Design School in Mexico.
He’s a mentor at the start-up incubator MATTER Chicago and an Emerging
Leader Fellow with The Chicago Council on Global Affairs.

Steve holds a BS in Mechanical Engineering from the University of Michigan
and a Master of Design from the IIT Institute of Design. He loves food,
travel and tennis. Born and raised in Detroit, he’s lived in Seoul,
Philadelphia and most recently in Chicago.



On Wed, Nov 4, 2015 at 7:14 PM, Ross Dakin <notifications@github.com> wrote:

> I can't see red.
>
> Can you callout the changes in a different way or just send the full text
> with your changes included?
>
> On Wednesday, November 4, 2015, Steven Babitch <notifications@github.com>
> wrote:
>
> > Oh sorry! I just meant use that content as the newer version. All black
> > text for sure.
> >
> > Sent from my iPhone
> >
> > On Nov 4, 2015, at 7:04 PM, Ross Dakin <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > @sbabitch <https://github.com/sbabitch> — color got stripped.
> >
> > Email me directly or call out in another way?
> >
> > Or just send me the full text anew.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> >
> https://github.com/presidential-innovation-fellows/pif-website/pull/87#issuecomment-153909907
> > >
> > .
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/presidential-innovation-fellows/pif-website/pull/87#issuecomment-153911549
> >
> > .
> >
>
>
> --
>
> Ross Dakin
> Presidential Innovation Fellow
> whitehouse.gov/innovationfellows
> (202) 286-0143
> ross.dakin@pif.gov
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/presidential-innovation-fellows/pif-website/pull/87#issuecomment-153912360>
> .
>



-- 
Presidential Innovation Fellow
White House Presidential Innovation Fellows
https://www.whitehouse.gov/innovationfellows
202.344.5806

**Comment by rossdakin** [comment]
How 'bout now?

----
screen shot 2015-11-04 at 9 36 05 pm

----
screen shot 2015-11-04 at 9 36 13 pm

**Comment by sbabitch** [comment]
Looks great... thanks Ross!

Sent from my iPhone

On Nov 4, 2015, at 9:37 PM, Ross Dakin <notifications@github.com> wrote:

How 'bout now?
------------------------------

[image: screen shot 2015-11-04 at 9 36 05 pm]
<https://cloud.githubusercontent.com/assets/44956/10958456/37fc9ad0-833c-11e5-9a1d-30be0d44b514.png>
------------------------------

[image: screen shot 2015-11-04 at 9 36 13 pm]
<https://cloud.githubusercontent.com/assets/44956/10958457/3acacafc-833c-11e5-9c40-e31ed5a5b9fa.png>

—
Reply to this email directly or view it on GitHub
<https://github.com/presidential-innovation-fellows/pif-website/pull/87#issuecomment-153935385>
.

**Comment by sbabitch** [comment]
Anything I need to do to make it go live?

On Wed, Nov 4, 2015 at 9:59 PM, Ross Dakin <notifications@github.com> wrote:

> Merged #87
> <https://github.com/presidential-innovation-fellows/pif-website/pull/87>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/presidential-innovation-fellows/pif-website/pull/87#event-455276257>
> .
>



-- 
Presidential Innovation Fellow
White House Presidential Innovation Fellows
https://www.whitehouse.gov/innovationfellows
202.344.5806

**Comment by rossdakin** [comment]
Nope. I'll push it today (or Stroup can).

On Thursday, November 5, 2015, Steven Babitch <notifications@github.com>
wrote:

> Anything I need to do to make it go live?
>
> On Wed, Nov 4, 2015 at 9:59 PM, Ross Dakin <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Merged #87
> > <https://github.com/presidential-innovation-fellows/pif-website/pull/87
> >.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/presidential-innovation-fellows/pif-website/pull/87#event-455276257
> >
> > .
> >
>
>
>
> --
> Presidential Innovation Fellow
> White House Presidential Innovation Fellows
> https://www.whitehouse.gov/innovationfellows
> 202.344.5806
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/presidential-innovation-fellows/pif-website/pull/87#issuecomment-154066164>
> .
>


-- 

Ross Dakin
Presidential Innovation Fellow
whitehouse.gov/innovationfellows
(202) 286-0143
ross.dakin@pif.gov

**Pull request merged**
